name: Rust

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USER }}
          server:  ${{ secrets.SSH_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './target/release/testauskoira-rs'
          remote_path: ${{ secrets.SSH_DIR }}
          args: '-o ConnectTimeout=5'
      - name: Restart testauskoira
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            screen -S testauskoira-rs -X quit
            screen -d -m -S testauskoira-rs bash -c "${{ secrets.SSH_DIR }}/testauskoira-rs"
