name: Rust

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install database
        run: mysql mysql -u root -proot -h 127.0.0.1 < database.sql
      - name: Build
        run: cargo build --release
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/Testauskoira
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USER }}
          server:  ${{ secrets.SSH_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './target/release/testauskoira-rs'
          remote_path: ${{ secrets.SSH_DIR }}
          args: '-o ConnectTimeout=5'
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            screen -S testauskoira-rs -X quit
            screen -d -m -S testauskoira-rs bash -c " ${{ secrets.SSH_DIR }}/testauskoira-rs"
